// <auto-generated />
using System;
using APIGastosPersonales.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIGastosPersonales.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251009200045_Pepito")]
    partial class Pepito
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APIGastosPersonales.Models.Categoria", b =>
                {
                    b.Property<int>("Id_categoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_categoria"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id_categoria");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id_categoria = 1,
                            Nombre = "Alimentacion",
                            Tipo = "Gasto"
                        },
                        new
                        {
                            Id_categoria = 2,
                            Nombre = "Transporte",
                            Tipo = "Gasto"
                        },
                        new
                        {
                            Id_categoria = 3,
                            Nombre = "Entretenimiento",
                            Tipo = "Gasto"
                        },
                        new
                        {
                            Id_categoria = 4,
                            Nombre = "Educación",
                            Tipo = "Gasto"
                        },
                        new
                        {
                            Id_categoria = 5,
                            Nombre = "Salud",
                            Tipo = "Gasto"
                        },
                        new
                        {
                            Id_categoria = 6,
                            Nombre = "Otros",
                            Tipo = "Gasto"
                        },
                        new
                        {
                            Id_categoria = 7,
                            Nombre = "Salario",
                            Tipo = "Ingreso"
                        },
                        new
                        {
                            Id_categoria = 8,
                            Nombre = "Venta",
                            Tipo = "Ingreso"
                        },
                        new
                        {
                            Id_categoria = 9,
                            Nombre = "Intereses",
                            Tipo = "Ingreso"
                        },
                        new
                        {
                            Id_categoria = 10,
                            Nombre = "Regalo",
                            Tipo = "Ingreso"
                        },
                        new
                        {
                            Id_categoria = 11,
                            Nombre = "Reembolso",
                            Tipo = "Ingreso"
                        },
                        new
                        {
                            Id_categoria = 12,
                            Nombre = "Otros",
                            Tipo = "Ingreso"
                        });
                });

            modelBuilder.Entity("APIGastosPersonales.Models.Cuenta", b =>
                {
                    b.Property<int>("Id_cuenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_cuenta"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("SaldoActual")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SaldoInicial")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id_cuenta");

                    b.ToTable("Cuentas");
                });

            modelBuilder.Entity("APIGastosPersonales.Models.Gasto", b =>
                {
                    b.Property<int>("Id_gasto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_gasto"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<int>("CuentaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id_gasto");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("CuentaId");

                    b.ToTable("Gastos");
                });

            modelBuilder.Entity("APIGastosPersonales.Models.Ingreso", b =>
                {
                    b.Property<int>("Id_ingreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_ingreso"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<int>("CuentaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id_ingreso");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("CuentaId");

                    b.ToTable("Ingresos");
                });

            modelBuilder.Entity("APIGastosPersonales.Models.Gasto", b =>
                {
                    b.HasOne("APIGastosPersonales.Models.Categoria", "Categoria")
                        .WithMany("Gastos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIGastosPersonales.Models.Cuenta", "Cuenta")
                        .WithMany("Gastos")
                        .HasForeignKey("CuentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Cuenta");
                });

            modelBuilder.Entity("APIGastosPersonales.Models.Ingreso", b =>
                {
                    b.HasOne("APIGastosPersonales.Models.Categoria", "Categoria")
                        .WithMany("Ingresos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIGastosPersonales.Models.Cuenta", "Cuenta")
                        .WithMany("Ingresos")
                        .HasForeignKey("CuentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Cuenta");
                });

            modelBuilder.Entity("APIGastosPersonales.Models.Categoria", b =>
                {
                    b.Navigation("Gastos");

                    b.Navigation("Ingresos");
                });

            modelBuilder.Entity("APIGastosPersonales.Models.Cuenta", b =>
                {
                    b.Navigation("Gastos");

                    b.Navigation("Ingresos");
                });
#pragma warning restore 612, 618
        }
    }
}
